# Site settings
title: SaaienTist
url: "http://jandot.github.io"
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  SaaienTist blog 2.0, probably on personal productivity, programming, data science. And other stuff.

# Your information
email: jan.aerts@gmail.com
author: Jan Aerts
#avatar: "//www.gravatar.com/avatar/jan.aerts@gmail.com"
profile: Professor Data Science & Visual Analytics.
twitter_username: jandot
github_username:  jandot
profile_links:
  Email: "mailto:jan.aerts@gmail.com"
  # GitHub: "https://github.com/jandot"
  # You can add more profile links above, or edit _includes/sidebar.html

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Categories: /category/

permalink: /:year/:month/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
